apiVersion: v1
kind: Secret
metadata:
  namespace: sdelval
  name: database-secret
  labels:
    app: backend-database
type: Opaque
stringData:
  database-user: user
  database-root-password: password1234.
  database-password: password1234.
  database-name: clients

---

apiVersion: v1
kind: Secret
metadata:
  namespace: sdelval
  name: api-secret
  labels:
    app: backend-api
type: Opaque
stringData:
  api-root-path: ""

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sdelval
  name: backend-database-configmap
data:
  database_url: backend-database-service